# Generated by Django 4.2.13 on 2024-06-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('basic_info_code', models.AutoField(primary_key=True, serialize=False)),
                ('registrant', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('purpose', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_code', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('registrant', models.CharField(max_length=100)),
                ('delete_flag', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('impression', models.TextField()),
                ('learning', models.TextField()),
                ('basic_info_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrecord.basicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PostReadingSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('impression', models.TextField()),
                ('learning', models.TextField()),
                ('satisfaction_level', models.IntegerField()),
                ('note', models.TextField()),
                ('basic_info_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrecord.basicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info_code', models.CharField(max_length=100)),
                ('book_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrecord.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrecord.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrecord.genre'),
        ),
        migrations.CreateModel(
            name='BasicInfoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrecord.basicinfo')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrecord.tag')),
            ],
        ),
    ]
