# Generated by Django 4.2.13 on 2024-06-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='buy_reason',
            field=models.TextField(default='genre1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(choices=[('genre1', 'ジャンル1'), ('genre2', 'ジャンル2'), ('genre3', 'ジャンル3')], max_length=100),
        ),
    ]
