# Generated by Django 4.2.13 on 2024-06-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0005_remove_book_genres_book_basic_info_code_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingnote',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
