# Generated by Django 4.2.13 on 2024-06-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0008_alter_postreadingsummary_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='basic_info_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrecord.basicinfo'),
        ),
    ]
