# Generated by Django 4.2.13 on 2024-09-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0012_book_author_book_publisher_alter_basicinfo_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreadingsummary',
            name='impression',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postreadingsummary',
            name='learning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postreadingsummary',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
