# Generated by Django 4.2.13 on 2024-09-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0013_alter_postreadingsummary_impression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
