version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: my_django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: mysql_pass
      MYSQL_ROOT_PASSWORD: root_pass  
    ports:
      - "3306:3306"

volumes:
  static_volume:
  media_volume:
